version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json
    volumes:
      - ./backend/google-credentials.json:/app/google-credentials.json:ro
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend 